# Generated by Django 5.0.1 on 2024-02-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_alter_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=2011, upload_to='images/'),
            preserve_default=False,
        ),
    ]
